### ISSUE TITLE
Fatal error: Index out of range

### ISSUE THREAD

**Issue by Salmancs43** [EngrAhsanAli/AAPickerView#10]
Hi
It's crashes when there is no value in array. I have also implemented the check but it's not working. I have attached the screenshot. let me know what I am doing wrong in it. 
Thanks
<img width="571" alt="Screenshot 2020-06-03 at 11 56 38 AM" src="https://user-images.githubusercontent.com/23050315/83605417-4e41d680-a591-11ea-981c-7225f9c47d3e.png">

**Comment by EngrAhsanAli** [comment]
You must provide data in string array as it supposed to work with given string collection.

`picker.pickerType = .string(data: #String collection#)`
