### ISSUE TITLE
string picker issue

### ISSUE THREAD

**Issue by atriatech94** [EngrAhsanAli/AAPickerView#3]
doesn't show any option in swift 4
![simulator screen shot - iphone 8 - 2017-10-31 at 17 53 05](https://user-images.githubusercontent.com/11029971/32228765-697f5f60-be64-11e7-8eac-948a790c6b84.png)

**Comment by swiftymarks** [comment]
Same here

**Comment by AmirDaliri** [comment]
i have this issue

**Comment by ahmedsafadii** [comment]
have same issue 

but if you want make it works, change the swift version to 3.2 for this library and it will do the trick :D

**Comment by EngrAhsanAli** [comment]
Hi everyone, thanks for updating me, I've fixed the issue and here's the new version of POD pod 'AAPickerView', '~> 0.1.2'
