### ISSUE TITLE
Toolbar hide

### ISSUE THREAD

**Issue by waseem-shah-ios** [EngrAhsanAli/AAPickerView#5]
In iPhone x 

in portrait mode:  textfield picker is open, toolbar is showing 
but When I change my phone into landscape toolbar is hide behind the picker view 

but when I change orientation again to portrait toolbar again showing.

in iPhone x picker view toolbar is not showing in landscape mode.
But its working fine in portrait mode.

**Comment by EngrAhsanAli** [comment]
Fixed in the new version, thanks for reporting.
