### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)

### ISSUE THREAD

**Issue by GTimofey** [EngrAhsanAli/AAPickerView#7]
Error occurs when assigning AAPickerType object AAPickerView
![image](https://user-images.githubusercontent.com/39026860/51502770-9ae7a000-1de8-11e9-83c5-c4984403ef11.png)

**Comment by hamza-faroooq** [comment]
when you assign the AAPickerView class to your textfield, make sure to set also its module to AAPickerView. by default its 'None'
